backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - label: "Home page"
        name: "home"
        file: "site/content/home.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Preface text', name: beforeBlogPreviews, widget: markdown}
          - label: 'Blog previews'
            name: blogPreviews
            widget: list
            fields:
              - label: 'Blog post'
                name: post
                widget: relation
                collection: blog
              - {label: 'Preview Image', name: previewImage, widget: image}
          - {label: 'Middle text', name: beforeBlogPreviews, widget: markdown}
          - label: 'Project previews'
            name: projectPreviews
            widget: list
            fields:
              - label: 'Project'
                name: project
                widget: relation
                collection: projects
              - {label: 'Preview Image', name: previewImage, widget: image}
          - {label: 'Postface', name: beforeBlogPreviews, widget: markdown}